language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sksk571/docker-react -f ./Dockerfile.dev .
script:
  - docker run -e CI=true sksk571/docker-react npm run test -- --coverage