language: generic
services:
  - docker

before_install:
  - docker build -t sksk571/docker-react -f ./Dockerfile.dev .
script:
  - docker run -e CI=true sksk571/docker-react npm run test -- --coverage

deploy:
  provider: azure_web_apps
  site: "sksk571-docker-react"
  edge: true
  verbose: true
  on:
    branch: master