language: generic
services:
  - docker

before_install:
  - docker build -t sksk571/docker-react -f ./Dockerfile.dev .
script:
  - docker run -e CI=true sksk571/docker-react npm run test -- --coverage

deploy:
  provider: script
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push sksk571/docker-react
  on:
    branch: master